channels:
  - conda-forge
  - bioconda
dependencies:
  - r-base=4.1.3
  - bioconductor-deseq2=1.34.0
  - r-tidyverse=1.3.1
  - r-optparse=1.7.1
  - r-cli=3.6.0
  - r-here=1.0.1
  - r-knitr=1.37
  - r-tibble=3.1.6
  - r-stringr=1.4.0
  - r-dt
  - r-devtools # used for building, remove in final container