channels:
    - conda-forge
    - bioconda
    - r
    - defaults
dependencies:
    - python==3.10
    - jupyter
    - seaborn
    - plotly
    - matplotlib
    - pandas==1.5.0
    - scikit-learn 
    - statsmodels 
    - papermill
    - r-base==4.1.2 
    - bioconductor-deseq2=1.34.0
    - r-tidyverse==1.3.1 
    - r-plotly 
    - r-knitr 
    - r-stringi
    - r-irkernel
